project:
  type: website
  output-dir: _site
  resources:
    - "manual/**"
    - "vignettes/**"
    - "examples/**"
    - "blog/**"
    - "src/**"
    - feed
    

website:
  title: "NIMBLE"
  description: "An R package for programming with BUGS models and compiling parts of R"
  site-url: "https://r-nimble.org"
  repo-url: "https://github.com/nimble-dev/nimble"
  
  navbar:
    logo: "images/nimble-logo-oval-small-clean.png"
    logo-href: "index.qmd"
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "What is NIMBLE?"
        href: what-is-nimble.qmd
      - text: "Examples"
        href: examples.qmd
      - text: "Documentation"
        href: documentation.qmd
      - text: "Download"
        href: download.qmd
      - text: "Community"
        href: groups-and-issues.qmd
      - text: "Blog"
        menu:
          - text: "All Posts"
            href: blog/index.qmd
          - text: "---"
          - text: "Recent Posts"
          - text: "Version 1.4.0 and nimble Quad Released"
            href: blog/version-1-4-0-of-nimble-released.qmd
          - text: "nimbleMacros Package"
            href: blog/announcing-the-nimblemacros-package-and-the-use-of-macros-in-nimble-models.qmd
      - text: "More"
        menu:
          - text: "How to Contribute"
            href: contributing.qmd
          - text: "Release Notes"
            href: release-notes.qmd
          - text: "License and Citation"
            href: license-and-citation.qmd
          - text: "About Us"
            href: about-us.qmd
    
    tools:
      - icon: github
        href: "https://github.com/nimble-dev/nimble"
      - icon: twitter
        href: "https://twitter.com/R_nimble"
      - icon: rss
        href: blog/index.xml

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Blog Posts"
        contents:
          - text: "All Posts"
            href: blog/index.qmd
          - text: "---"
          - text: "Recent Posts"
          - blog/version-1-4-0-of-nimble-released.qmd 
          - blog/announcing-the-nimblemacros-package-and-the-use-of-macros-in-nimble-models.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    toc-location: right
    code-copy: true
    code-overflow: wrap
    page-layout: article
